Parameters:
  VPC:
    Description: Attache the VPC
    Type: AWS::EC2::VPC::Id
  Subnets:
    Description: My Subnets
    Type: List<AWS::EC2::Subnet::Id>
  SG:
    Description: My SecurityGroup
    Type: AWS::EC2::SecurityGroup::Id
Resources:
  myASG:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      AutoScalingGroupName: My Auto Scaling Group
      VPCZoneIdentifier:
       - !Select [ 0, !Ref Subnets ]
       - !Select [ 1, !Ref Subnets ]
       - !Select [ 2, !Ref Subnets ]
      Cooldown: 300
      MinSize: 1
      MaxSize: 2
      DesiredCapacity: 1
      HealthCheckGracePeriod: 300
      LaunchTemplate:
        LaunchTemplateId: !Ref myLaunchTemplate
        Version: 1
      # LoadBalancerNames: !Ref LoadBalancer
      TargetGroupARNs:
        - Ref: TargetGroup
        # - arn:aws:elasticloadbalancing:eu-central-1:482720962971:targetgroup/TargetGroupTigranHambardzumyan/ef9c74ba081f1061  
      Tags:
        - Key: Name
          Value: TigranHambardzumyan
          PropagateAtLaunch: "true"
        - Key: ResourceName
          Value: TigranHambardzumyan
          PropagateAtLaunch: "true"
  
  myLaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties: 
      LaunchTemplateName: !Sub ${AWS::StackName}-launch-template
      LaunchTemplateData: 
        ImageId: ami-05f7491af5eef733a
        InstanceType: t2.micro
        KeyName: Tigran
        SecurityGroupIds: 
          - !Ref SG 
        UserData:
           Fn::Base64: !Sub |
              #!/bin/bash
              sudo apt update -y
              sudo apt upgrade -y
              sudo apt install -y apache2
              sudo systemctl start apache2
              sudo systemctl enable apache2
              sudo chmod 777 /var/www/html -R
              sudo echo "<h1>This is the host Name: $(hostname -f)</h1>" > /var/www/html/index.html

  LoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      IpAddressType: ipv4
      Name: NetworkLB
      Scheme: internet-facing
      Subnets:
        - !Select [ 0, !Ref Subnets ]
        - !Select [ 1, !Ref Subnets ]
        - !Select [ 2, !Ref Subnets ]
      Type: network
     
  Listener:
    Type: 'AWS::ElasticLoadBalancingV2::Listener'
    Properties:
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref TargetGroup
      LoadBalancerArn: !Ref LoadBalancer
      Port: 80
      Protocol: TCP     
     
  TargetGroup:
    Type: 'AWS::ElasticLoadBalancingV2::TargetGroup'
    Properties:
      Name: !Sub ${AWS::StackName}-TargetGroup
      Port: 80
      Protocol: TCP
      VpcId: !Ref VPC     
     
     
